site_name: DockDogs Scheduling
pages:
- Home: index.md
- Get Started:
    - Basics and Introduction: getting-started/basics-and-introduction.md 
    - Status Identifiers: getting-started/status-identifiers.md
    - FAQS: getting-started/FAQs.md
- Reporting:
    - Reporting Basics: reporting/reporting-basics.md
    - Pre-Built Sponsors Report: reporting/pre-built-sponsors-report.md 
    - Events Team Reports: reporting/events-team-reports.md
    - Other Reports: reporting/other-reports.md 
- Notifications:
    - Pre-Built Notifications: notifications/pre-build-notifications.md
theme: readthedocs

markdown_extensions:
    - toc:
        permalink: 
    - admonition: