site_name: DockDogs Scheduling
pages:
- Home: index.md
- Getting Started
	- Basics and Introduction: getting-started/Basics and Introduction.md
	- Status Icon Legend: Status Icon Legend.md
	- FAQS: getting-started/FAQs.md
- Reporting
	- Reporting Basics: Reporting Basics.md
	- Creating A New Report: reporting/Creating A New Report.md
	- Pre-Built Sponsors Report: Pre-Built Sponsors Report.md
- Notifications
	- Pre-Built Notifications: notifications/Pre-Built Notifications.md
	- Notification Basics: notifications/Notifications Basics.md


theme: readthedocs

copyright: Copyright &copy; 2015 <a href="https://twitter.com/brianjking">Brian J King</a>

